{% set name = "rustimport" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rustimport-{{ version }}.tar.gz
  sha256: 6349461ab131ccf925b07cf58c9c535525b17e1bbb7582718020c1ec7e043e40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - toml >=0.10.2

test:
  imports:
    - rustimport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mityax/rustimport
  summary: Import Rust files directly from Python!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
