{% set name = "rustimport" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rustimport-{{ version }}.tar.gz
  sha256: 980f01d6d286c64462edd37cce468227010b0376b4ade13590ed8ab181460355

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - toml >=0.10.2

test:
  imports:
    - rustimport
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mityax/rustimport
  summary: Import Rust files directly from Python!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
