{% set name = "rustimport" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rustimport-{{ version }}.tar.gz
  sha256: ba80e3c28af07ba3910ad395613d01f9e421bfb59fbb1ac050e2b5d9b78b4980

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - toml >=0.10.2

test:
  imports:
    - rustimport
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mityax/rustimport
  summary: Import Rust files directly from Python!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
